# build stage
FROM node:12.2.0-alpine as build
WORKDIR /Labrise
ENV PATH /Labrise/node_modules/.bin:$PATH
COPY package.json /Labrise/package.json
RUN npm install --silent
COPY . /Labrise
RUN npm run build

# final stage
FROM nginx:1.16.0-alpine
COPY --from=build /Labrise/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]