export const READ_BEETLEINFO_SUCCESSFUL = 'READ_BEETLEINFO_SUCCESSFUL';
export const READ_BEETLEINFO_PENDING = 'READ_BEETLEINFO_PENDING';
export const READ_BEETLEINFO_FAILURE = 'READ_BEETLEINFO_FAILURE';