export const READ_MODALDATA_SUCCESFUL = 'READ_MODALDATA_SUCCESFUL';
export const READ_MODALDATA_PENDING = 'READ_MODALDATA_PENDING';
export const READ_MODALDATA_FAILURE = 'READ_MODALDATA_FAILURE';
export const UPDATE_MODAL_DATA_STRING= 'UPDATE_MODAL_DATA_STRING';